# Generated by Django 3.1.1 on 2020-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_damage_type_device_type_pickup_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('device_type', models.CharField(choices=[('iphone 2', 'Iphone2'), ('samsung s2', 'samsung s2')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Damage_Type',
        ),
        migrations.DeleteModel(
            name='Device_Type',
        ),
        migrations.DeleteModel(
            name='Pickup',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
    ]
