# Generated by Django 3.1.1 on 2020-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201108_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairs',
            name='device_type',
            field=models.CharField(choices=[('phone ', 'Phone'), ('tv', 'Tv'), ('laptop', 'Laptop')], max_length=100),
        ),
    ]
