# Generated by Django 3.1.1 on 2020-11-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_repairs_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repairs',
            new_name='Repair',
        ),
    ]
